include ../../support/include.mk
EBIN_DIR := ../../ebin
DOC_DIR  := ../../doc

DIRS = fake lan script library

all:
	cd fake; $(MAKE)
	cd lan; $(MAKE)
	cd script; $(MAKE)
	cd library; $(MAKE)

debug:

clean:
